export const c = {
  bg:          "var(--bg)",
  surface:     "var(--surface)",
  surface2:    "var(--surface-2)",
  border:      "var(--border)",
  borderOpq:   "var(--border-opaque)",
  text:        "var(--text)",
  textSec:     "var(--text-secondary)",
  textMuted:   "var(--text-muted)",
  fill:        "var(--fill)",
  accent:      "var(--accent)",
  accentLight: "var(--accent-light)",
  accentText:  "var(--accent-text)",
  success:     "var(--success)",
  successBg:   "var(--success-bg)",
  successText: "var(--success-text)",
  danger:      "var(--danger)",
  dangerBg:    "var(--danger-bg)",
  dangerText:  "var(--danger-text)",
  shadow:      "var(--shadow)",
  shadowMd:    "var(--shadow-md)",
};
